#include "gsm/add.c"
#include "gsm/code.c"
#include "gsm/debug.c"
#include "gsm/decode.c"
#include "gsm/gsm_create.c"
#include "gsm/gsm_decode.c"
#include "gsm/gsm_destroy.c"
#include "gsm/gsm_encode.c"
#include "gsm/long_term.c"
#include "gsm/lpc.c"
#include "gsm/preprocess.c"
#include "gsm/rpe.c"
#include "gsm/short_term.c"
#include "gsm/table.c"

